name: Build and upload

on:
  push:
    branches: ["*"]
  workflow_dispatch: {}

jobs:
  concierge-graphql:
    runs-on: ubuntu-latest

    # The first two permissions are needed to interact with GitHub's OIDC Token endpoint.
    # The second set of three permissions are needed to write test results back to GH
    permissions:
      id-token: write
      contents: read
      issues: read
      checks: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: sbt

      - name: Build and test
        env:
          SBT_JUNIT_OUTPUT: ./junit-tests
          JAVA_OPTS: -Dsbt.log.noformat=true
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          sbt 'test;docker:publishLocal'

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()  #runs even if there is a test failure
        with:
          files: junit-tests/*.xml