name: Build and upload

on:
  push:
    branches: ["*"]
  workflow_dispatch: {}

jobs:
  concierge-graphql-gnm:
    runs-on: ubuntu-latest

    # The first two permissions are needed to interact with GitHub's OIDC Token endpoint.
    # The second set of three permissions are needed to write test results back to GH
    permissions:
      id-token: write
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: cdk/yarn.lock

#      - run: yarn install --frozen-lockfile
#        name: Prepare to build explorer
#        working-directory: explorer
#
#      - run: yarn build
#        name: Build explorer
#        working-directory: explorer

      - run: yarn install --frozen-lockfile
        name: Prepare for CDK infrastructure build
        working-directory: cdk
      - run: yarn test
        name: Test CDK infrastructure integrity
        working-directory: cdk
      - run: yarn synth
        name: Build infrastructure definition from CDK
        working-directory: cdk

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-region: eu-west-1
#          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
#          role-session-name: content-api-concierge-graphql-build

      - name: Build and test
        env:
          SBT_JUNIT_OUTPUT: ./junit-tests
          JAVA_OPTS: -Dsbt.log.noformat=true
        run: |
          sbt 'test;debian:packageBin'
      - uses: guardian/actions-riff-raff@v4
        with:
          configPath: ./riff-raff.yaml
          projectName: Content Platforms::concierge-graphql-experimental
          contentDirectories: |
            concierge-graphql:
              - target/concierge-graphql_0.1.0_all.deb
            cloudformation:
              - cdk/cdk.out/ConciergeGraphql-PROD-AARDVARK.template.json
              - cdk/cdk.out/ConciergeGraphql-CODE-AARDVARK.template.json
            cloudformation-preview:
              - cdk/cdk.out/ConciergeGraphql-preview-PROD-AARDVARK.template.json
              - cdk/cdk.out/ConciergeGraphql-preview-CODE-AARDVARK.template.json
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()  #runs even if there is a test failure
        with:
          files: junit-tests/*.xml